#!/bin/bash
for (( i=0; i<$1; i++))
do
    make
    ./test >> output.txt
done

arr=()
while IFS= read -r line; do
    arr+=("$line")
done <output.txt
arr1=(); arr2=(); arr3=()
for (( i=0; i<${#arr[@]}; i++ )); do
    words=(${arr[i]})
    status=${words[1]}
    if [[ ${words[0]} == "'test_1_2'" ]]; then
        arr1+=("$status");
    elif  [[ "${words[0]}" == "'test2'" ]]; then
        arr2+=("$status");
    elif  [[ "${words[0]}" == "'test3'" ]]; then
        arr3+=("$status");
    fi
done
counter=(0 0 0)

for (( i=0; i<${#arr1[@]}; i++ )); do
    if [[ ${arr1[i]} == "PASSED" ]]; then
        counter[0]=$((counter[0]+1))
    fi
done
for (( i=0; i<${#arr2[@]}; i++ )); do
    if [[ ${arr2[i]} == "PASSED" ]]; then
        counter[1]=$((counter[1]+1))
    fi
done
for (( i=0; i<${#arr3[@]}; i++ )); do
    if [[ ${arr3[i]} == "PASSED" ]]; then
        counter[2]=$((counter[2]+1))
    fi
done
echo "Test 1 passed ${counter[0]}/${#arr1[@]} times"
echo "Test 2 passed ${counter[1]}/${#arr2[@]} times"
echo "Test 3 passed ${counter[2]}/${#arr3[@]} times"
rm output.txt